### ISSUE TITLE
Errors when trying to generate new code

### ISSUE THREAD

**Issue by pasotee** [dyc3/steamguard-cli#157]
Hey there, 

First of all, thanks a lot for this awesome tool! We've been using it using it in our CI/CD pipeline for the past 2 months.
However halfway through today it started throwing this error with nothing changed in the configuration files.
I've tried running with v0.4.5, v0.4.4 and v0.4.3 all with the same result, as well as multiple different machines.

Note: Trying to generate the code does work in 1/10 times

Logs with `RUST_BACKTRACE=full` attached below:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }', steamguard/src/steamapi.rs:115:57
stack backtrace:
   0:           0x6c88ab - std::backtrace_rs::backtrace::libunwind::trace::h081201764674ef17
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:           0x6c88ab - std::backtrace_rs::backtrace::trace_unsynchronized::hebab37398c391bd7
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:           0x6c88ab - std::sys_common::backtrace::_print_fmt::h301516df68ed24f9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:           0x6c88ab - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f5170f4f03a12c0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:           0x4850bc - core::fmt::write::h5dc5601e8d9f6367
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:           0x6a3379 - std::io::Write::write_fmt::h5b19302eb99d9acf
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:           0x6c9a62 - std::sys_common::backtrace::_print::hd81cf53a75c8ae6a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:           0x6c9a62 - std::sys_common::backtrace::print::hb5aa882e87c2a0dc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:           0x6c9a62 - std::panicking::default_hook::{{closure}}::had913369af61b326
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:           0x6caaaa - std::panicking::default_hook::h37b06af9ee965447
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:           0x6caaaa - std::panicking::rust_panic_with_hook::hf2019958d21362cc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:           0x6ca4f2 - std::panicking::begin_panic_handler::{{closure}}::he9c06fdd592f8785
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:           0x6ca466 - std::sys_common::backtrace::__rust_end_short_backtrace::ha521b96560789310
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:           0x6ca422 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:           0x4032d2 - core::panicking::panic_fmt::h28f1697d4e9394b4
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:           0x403622 - core::result::unwrap_failed::hea43ef43a7a8c801
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
  16:           0x6d840c - steamguard::steamapi::get_server_time::h248e35b135dc242a
  17:           0x7122e8 - steamguard_cli::run::h790ca69e9f9fbcec
  18:           0x70be2d - steamguard_cli::main::h9362cc0ca1804eab
  19:           0x7380a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h62d69c0dbe1a89a1
  20:           0x70b830 - main
```

Let me know if any other information would be useful

**Comment by dyc3** [comment]
Try running with a build from master.

**Comment by pasotee** [comment]
Thanks for the quick answer, it seems it was caused by steam beeing down. It's working fine right now, if it happends again, we will make a build from master.

Looking forward for v0.5.0 and thanks again for this awesome tool.
Closing this since #156 seems to be what we need indeed.
