### ISSUE TITLE
"Unexpected error when trying to log in." or "Failed to link authenticator. Account has not been linked. Invalid padding"

### ISSUE THREAD

**Issue by xDroflLOL** [dyc3/steamguard-cli#299]
### Version

0.10.4

### What happened?

I tried to setup another steam guard on an account, but instead of proceeding to adding my phone number, I either get 
```
ERROR - Unexpected error when trying to log in. If you report this as a bug, please rerun with `-v debug` or `-v trace` and include all output in your issue. UnknownEResult(ServiceUnavailable)
thread 'main' panicked at 'Failed to log in. Account has not been linked.: UnknownEResult(ServiceUnavailable)', src/commands/setup.rs:34:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 
or 
```
ERROR - Failed to link authenticator. Account has not been linked. Invalid padding
ERROR - Invalid padding
```

### Steps To Reproduce

1. Attempt to run setup (with debug)
2. Input username and password
3. See error

### Relevant log output

```Shell
DEBUG - Args { global: GlobalArgs { username: None, all: false, mafiles_path: None, passkey: None, verbosity: Debug, no_update_check: false, http_proxy: None, proxy_credentials: None, danger_accept_invalid_certs: false }, sub: Some(Setup(SetupCommand)), code: CodeCommand { offline: false } }
INFO - reading manifest from C:\Users\xyz\AppData\Roaming\steamguard-cli/maFiles
DEBUG - loading manifest: "C:\\Users\\xyz\\AppData\\Roaming\\steamguard-cli/maFiles\\manifest.json"
DEBUG - passkey was revoked from manifest
DEBUG - Performing auto-upgrade...
DEBUG - Manifest is up to date
Log in to the account that you want to link to steamguard-cli
Username: INFO - Logging in to ***********************
Password:
DEBUG - password is present
DEBUG - HTTP Request: GET https://api.steampowered.com/IAuthenticationService/GetPasswordRSAPublicKey/v1
DEBUG - Response HTTP status: 200 OK
DEBUG - HTTP Header x-eresult: 1
DEBUG - HTTP Request: POST https://api.steampowered.com/IAuthenticationService/BeginAuthSessionViaCredentials/v1
DEBUG - Response HTTP status: 200 OK
DEBUG - HTTP Header x-eresult: 20
ERROR - Unexpected error when trying to log in. If you report this as a bug, please rerun with `-v debug` or `-v trace` and include all output in your issue. UnknownEResult(ServiceUnavailable)
thread 'main' panicked at 'Failed to log in. Account has not been linked.: UnknownEResult(ServiceUnavailable)', src/commands/setup.rs:34:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

(later...)

DEBUG - Args { global: GlobalArgs { username: None, all: false, mafiles_path: None, passkey: None, verbosity: Debug, no_update_check: false, http_proxy: None, proxy_credentials: None, danger_accept_invalid_certs: false }, sub: Some(Setup(SetupCommand)), code: CodeCommand { offline: false } }
INFO - reading manifest from C:\Users\xyz\AppData\Roaming\steamguard-cli/maFiles
DEBUG - loading manifest: "C:\\Users\\xyz\\AppData\\Roaming\\steamguard-cli/maFiles\\manifest.json"
DEBUG - passkey was revoked from manifest
DEBUG - Performing auto-upgrade...
DEBUG - Manifest is up to date
Log in to the account that you want to link to steamguard-cli
Username: INFO - Logging in to ***********************
Password:
DEBUG - password is present
DEBUG - HTTP Request: GET https://api.steampowered.com/IAuthenticationService/GetPasswordRSAPublicKey/v1
DEBUG - Response HTTP status: 200 OK
DEBUG - HTTP Header x-eresult: 1
DEBUG - HTTP Request: POST https://api.steampowered.com/IAuthenticationService/BeginAuthSessionViaCredentials/v1
DEBUG - Response HTTP status: 200 OK
DEBUG - HTTP Header x-eresult: 5
ERROR - Incorrect password for ***********************
Password:
DEBUG - HTTP Request: GET https://api.steampowered.com/IAuthenticationService/GetPasswordRSAPublicKey/v1
DEBUG - Response HTTP status: 200 OK
DEBUG - HTTP Header x-eresult: 1
DEBUG - HTTP Request: POST https://api.steampowered.com/IAuthenticationService/BeginAuthSessionViaCredentials/v1
DEBUG - Response HTTP status: 200 OK
DEBUG - HTTP Header x-eresult: 1
DEBUG - auth session started
WARN - Unknown confirmation method: AllowedConfirmation { confirmation_type: k_EAuthSessionGuardType_None, associated_messsage: "" }
INFO - Polling for tokens... -- If this takes a long time, try logging in again.
DEBUG - HTTP Request: POST https://api.steampowered.com/IAuthenticationService/PollAuthSessionStatus/v1
DEBUG - Response HTTP status: 200 OK
DEBUG - HTTP Header x-eresult: 1
INFO - Logged in successfully!
INFO - Adding authenticator...
ERROR - Failed to link authenticator. Account has not been linked. Invalid padding
ERROR - Invalid padding
DEBUG - Checking for updates to dyc3/steamguard-cli v0.10.4
DEBUG - No update available
```

**Comment by dyc3** [comment]
`ServiceUnavailable` seems like a Valve issue. Nothing I can do about that.

The invalid padding one seems weird though, I'll take a look tomorrow morning.

**Comment by dyc3** [comment]
Ok, I can reproduce the invalid padding thing.
